# Setup
title:        scBASE
tagline:      Zero-and-One Inflated Model for estimating allelic proportion from scRNA-Seq data
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kwangbom "KB" Choi
  url:        https://www.jax.org/research-and-faculty/faculty/research-scientists/kb-choi

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
